import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: "../font/ppneuemontreal-book.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/ppneuemontreal-italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../font/ppneuemontreal-thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../font/ppneuemontreal-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../font/ppneuemontreal-bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
